# work-flow 名称 - 自动代码评审
name: Run Code Review

on:
  push:
    branches:
      - master-close
  pull_request:
    branches:
      - master-close

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # 检出最后两个修改 以便可以比较 HEAD~1 和 HEAD

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run Java code
        run: |
          cd openai-code-review-sdk/src/main/java
          javac org/ocr/com/OpenAiCodeReview.java
          java -cp . org.ocr.com.OpenAiCodeReview
